import NavBar from './NavBar'
import './globals.css'

export const metadata = {
  title: 'Postgres Practice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html className = 'bg-black text-white' lang="en">
      <body>
        <NavBar />  
        {children}
      </body>
    </html>
  )
}
