import NavBar from './NavBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Postgres Practice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html className = 'bg-black text-white' lang="en">
      <body className = {inter.className}>
        <NavBar />  
        {children}
      </body>
    </html>
  )
}
